// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static void aCT_CreateTest(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_CreateTest").withParams(params).execute(context);
	}
	public static void aCT_CreateTest2(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("MyFirstModule.ACT_CreateTest2").withParams(params).execute(context);
	}
	public static void aCT_LoadSomethingSlowly(IContext context, myfirstmodule.proxies.AsyncDataLoader _asyncDataLoader, myfirstmodule.proxies.MainEntity _mainEntity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AsyncDataLoader", _asyncDataLoader == null ? null : _asyncDataLoader.getMendixObject());
		params.put("MainEntity", _mainEntity == null ? null : _mainEntity.getMendixObject());
		Core.microflowCall("MyFirstModule.ACT_LoadSomethingSlowly").withParams(params).execute(context);
	}
	public static void dS_GetListSlowly(IContext context, myfirstmodule.proxies.AsyncDataLoader _asyncDataLoader, myfirstmodule.proxies.MainEntity _mainEntity)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("AsyncDataLoader", _asyncDataLoader == null ? null : _asyncDataLoader.getMendixObject());
		params.put("MainEntity", _mainEntity == null ? null : _mainEntity.getMendixObject());
		Core.microflowCall("MyFirstModule.DS_GetListSlowly").withParams(params).execute(context);
	}
}
